import 'dotenv/config';

const {
  PORT = '4000',
  DB_URL,
  REDIS_CONNECTION_STRING,
  GOOGLE_CLIENT_ID,
  GMAIL_USER,
  GMAIL_APP_PASSWORD,
  SESSION_SECRET,
  CLIENT_URL,
  S3_ACCESS_KEY,
  S3_SECRET_KEY,
  CLOUDFRONT_KEY_ID,
} = process.env;

export {
  DB_URL as DATABASE_CONNECTION_STRING,
  REDIS_CONNECTION_STRING,
  GOOGLE_CLIENT_ID,
  GMAIL_USER as NODEMAILER_GMAIL_USER,
  GMAIL_APP_PASSWORD as NODEMAILER_GMAIL_APP_PASSWORD,
  SESSION_SECRET,
  CLIENT_URL as CLIENT_APP_URL,
  S3_ACCESS_KEY,
  S3_SECRET_KEY,
  CLOUDFRONT_KEY_ID,
  PORT
};
